### ISSUE TITLE
scaffold_bilstm_attention_classifier is not a registered name for Model

### ISSUE THREAD

**Issue by Tristan-Chow** [allenai/scicite#6]
Hi, I try to run your pretrained SciCite model on my own data, my command is like 
!allennlp predict $path_to_model $path_to_data \
$predictor \
scicite \
"{'model':{'data_format':''}}" \
$output_path 
And then it gives me an error like 'allennlp.common.checks.ConfigurationError: 'scaffold_bilstm_attention_classifier is not a registered name for Model'
I am wondering what the solution may be, thanks!

**Comment by Tristan-Chow** [comment]
!allennlp predict \
    ./scicite/scicite.tar.gz \
    ../data/train.jsonl.jsonl \
    --predictor predictor_scicite \
    --include-package scicite \
    --overrides "{'model':{'data_format':''}}"
Now I rewrite my code and the error is
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/__init__.py", line 71, in main
    import_submodules(package_name)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/util.py", line 290, in import_submodules
    path_string = '' if not path else path[0]
TypeError: '_NamespacePath' object does not support indexing
Thank you!

**Comment by armancohan** [comment]
What allennlp version are you using?

**Comment by Tristan-Chow** [comment]
I just run requirements.in before running the code, so I guess the version is default?

**Comment by Tristan-Chow** [comment]
The version is 0.8 0.8

**Comment by dwadden** [comment]
I ran into this. The issue for me was that the `scicite` package wasn't being found by `--include-package`. The solution for me was just to `cd` into the `scicite` directory, before executing `allennlp predict`.

**Comment by Mayar2009** [comment]
after running

!allennlp predict '/content/drive/My Drive/project/scicite-master/scicite.tar.gz' '/content/drive/My Drive/project/scicite/train.jsonl' --predictor predictor_scicite --include-package scicite --overrides "{'model':{'data_format':''}}"


got this error


/usr/local/lib/python3.6/dist-packages/allennlp/service/predictors/__init__.py:23: FutureWarning: allennlp.service.predictors.* has been depreciated. Please use allennlp.predictors.*
  "Please use allennlp.predictors.*", FutureWarning)
/usr/local/lib/python3.6/dist-packages/allennlp/service/predictors/predictor.py:6: FutureWarning: allennlp.service.predictors.* has been deprecated. Please use allennlp.predictors.*
  " Please use allennlp.predictors.*", FutureWarning)
2020-08-18 06:15:48,489 - INFO - allennlp.models.archival - loading archive file /content/drive/My Drive/project/scicite-master/scicite.tar.gz
2020-08-18 06:15:48,490 - INFO - allennlp.models.archival - extracting archive file /content/drive/My Drive/project/scicite-master/scicite.tar.gz to temp dir /tmp/tmpetky_ccd
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/__init__.py", line 72, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/predict.py", line 187, in _predict
    predictor = _get_predictor(args)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/predict.py", line 99, in _get_predictor
    overrides=args.overrides)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/models/archival.py", line 144, in load_archive
    config = Params.from_file(os.path.join(serialization_dir, CONFIG_NAME), overrides)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/params.py", line 376, in from_file
    params_file = cached_path(params_file)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/file_utils.py", line 103, in cached_path
    raise FileNotFoundError("file {} not found".format(url_or_filename))
FileNotFoundError: file /tmp/tmpetky_ccd/config.json not found
2020-08-18 06:16:00,890 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmpetky_ccd
